# Generated by Django 3.1.3 on 2022-02-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_s', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='original_url',
            field=models.URLField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='urlmodel',
            name='shortened_url',
            field=models.CharField(default='', max_length=15),
        ),
    ]
